name: Send API Requests Workflow

on:
  schedule:
    - cron: '* * * * *'  # Каждые 1 минуту

jobs:
  send_requests:
    runs-on: ubuntu-latest
    steps:
      - name: Send first POST request
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"id": "139awUEmUdTH8oi8mxeg9UkzWeFWKE645TcbITtb2pfA", "mapping":{"a":"vk"}, "list_name": "sb"}' \
            https://store.salebot.pro/function/gsheets

      - name: Send second POST request
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"id": "139awUEmUdTH8oi8mxeg9UkzWeFWKE645TcbITtb2pfA", "mapping":{"a":"tg"}, "list_name": "sb"}' \
            https://store.salebot.pro/function/gsheets

      - name: Send third POST request
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"id": "139awUEmUdTH8oi8mxeg9UkzWeFWKE645TcbITtb2pfA", "mapping":{"a":"youtube"}, "list_name": "sb"}' \
            https://store.salebot.pro/function/gsheets
